name: dynamic_row_table
description: A Flutter widget for building dynamic tables with multiple lines per cell.
version: 1.0.0
homepage: https://github.com/princetomar27/dynamic-text-table
repository: https://github.com/princetomar27/dynamic-text-table
issue_tracker: https://github.com/princetomar27/dynamic-text-table/issues
environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.0 # Adds linting for better code quality

flutter:
  uses-material-design: true
